# Generated by Django 4.2.7 on 2023-11-04 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pmid', models.AutoField(primary_key=True, serialize=False)),
                ('outstanding', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.patient')),
            ],
        ),
    ]
